"""
Synthetic email datasets for the three tasks.
Each email has a ground-truth label used by the grader.
"""

EASY_EMAILS = [
    {
        "id": "e001",
        "sender": "no-reply@casino-wins.biz",
        "subject": "YOU WON $5,000,000!!!",
        "body": "Congratulations! You have been selected as our lucky winner. Click here to claim your prize immediately.",
        "timestamp": "2024-01-15T08:00:00",
        "ground_truth": {"category": "spam", "priority": "low"},
    },
    {
        "id": "e002",
        "sender": "alice@company.com",
        "subject": "Q4 Budget Review - Action Required",
        "body": "Hi, the finance team needs the Q4 budget figures by EOD Friday. Please review the attached spreadsheet and confirm the numbers are correct. This is blocking our board presentation.",
        "timestamp": "2024-01-15T08:30:00",
        "ground_truth": {"category": "work", "priority": "urgent"},
    },
    {
        "id": "e003",
        "sender": "mom@gmail.com",
        "subject": "Dinner Sunday?",
        "body": "Hi honey, are you free for dinner on Sunday? Dad and I are making your favourite pasta. Let us know! Love, Mom",
        "timestamp": "2024-01-15T09:00:00",
        "ground_truth": {"category": "personal", "priority": "low"},
    },
    {
        "id": "e004",
        "sender": "devops@company.com",
        "subject": "ALERT: Production server down",
        "body": "CRITICAL: The main production server has been unresponsive for the past 10 minutes. Error rate is 100%. Customers are affected. Immediate action required.",
        "timestamp": "2024-01-15T09:15:00",
        "ground_truth": {"category": "work", "priority": "urgent"},
    },
    {
        "id": "e005",
        "sender": "newsletter@techcrunch.com",
        "subject": "TechCrunch Daily: Top Stories",
        "body": "Today's headlines: OpenAI releases new model, Apple earnings beat expectations, and more...",
        "timestamp": "2024-01-15T09:30:00",
        "ground_truth": {"category": "newsletter", "priority": "low"},
    },
    {
        "id": "e006",
        "sender": "bob@partner.com",
        "subject": "Contract renewal discussion",
        "body": "Hi, our contract expires next month. I'd love to set up a call to discuss renewal terms. Are you available this week?",
        "timestamp": "2024-01-15T10:00:00",
        "ground_truth": {"category": "work", "priority": "medium"},
    },
    {
        "id": "e007",
        "sender": "phishing@secure-bank-login.net",
        "subject": "Urgent: Your account has been compromised",
        "body": "Dear customer, we have detected suspicious activity. Click here to verify your account immediately or it will be suspended.",
        "timestamp": "2024-01-15T10:15:00",
        "ground_truth": {"category": "spam", "priority": "low"},
    },
    {
        "id": "e008",
        "sender": "hr@company.com",
        "subject": "Annual performance review scheduled",
        "body": "Your annual performance review has been scheduled for January 25th at 2 PM. Please complete the self-assessment form by January 22nd.",
        "timestamp": "2024-01-15T10:30:00",
        "ground_truth": {"category": "work", "priority": "medium"},
    },
    {
        "id": "e009",
        "sender": "jane@friend.com",
        "subject": "Birthday party this Saturday!",
        "body": "Hey! I'm having a birthday party this Saturday at my place starting at 7 PM. Would love for you to come! Let me know if you can make it.",
        "timestamp": "2024-01-15T11:00:00",
        "ground_truth": {"category": "personal", "priority": "low"},
    },
    {
        "id": "e010",
        "sender": "cto@company.com",
        "subject": "Architecture review - your input needed",
        "body": "Team, I need everyone's input on the proposed microservices architecture before tomorrow's board meeting. Please review the doc and add comments by 5 PM today.",
        "timestamp": "2024-01-15T11:15:00",
        "ground_truth": {"category": "work", "priority": "urgent"},
    },
    # ── New emails (Enhancement D) ─────────────────────────────────────────
    {
        "id": "e011",
        "sender": "coworker.sam@company.com",
        "subject": "Lunch today? Also quick question about the API",
        "body": "Hey! Want to grab lunch? Also, the new REST endpoint is returning 422 on valid payloads — could you take a look when you get a chance? Not blocking but would be nice to fix soon.",
        "timestamp": "2024-01-15T11:30:00",
        "ground_truth": {"category": "work", "priority": "medium"},
    },
    {
        "id": "e012",
        "sender": "noreply@linkedin.com",
        "subject": "Your weekly career update",
        "body": "See who's viewed your profile this week. 12 new job recommendations based on your skills. Update your profile to get more visibility.",
        "timestamp": "2024-01-15T11:45:00",
        "ground_truth": {"category": "newsletter", "priority": "low"},
    },
    {
        "id": "e013",
        "sender": "verify@paypa1-secure.com",
        "subject": "Action Required: Confirm your identity",
        "body": "We noticed unusual activity on your account. Please confirm your identity by clicking the link below within 24 hours or your account will be permanently locked. http://paypa1-secure.com/verify",
        "timestamp": "2024-01-15T12:00:00",
        "ground_truth": {"category": "spam", "priority": "low"},
    },
    {
        "id": "e014",
        "sender": "brother@gmail.com",
        "subject": "Moving help needed this weekend",
        "body": "Hey, I'm moving to my new apartment this Saturday morning. Could really use an extra pair of hands. I'll get pizza and beer afterwards! Let me know.",
        "timestamp": "2024-01-15T12:15:00",
        "ground_truth": {"category": "personal", "priority": "medium"},
    },
    {
        "id": "e015",
        "sender": "security@company.com",
        "subject": "URGENT: Mandatory password rotation",
        "body": "Per our new security policy, all employees must rotate their passwords by end of day. Failure to comply will result in account lockout. Use the internal portal at security.company.com/rotate.",
        "timestamp": "2024-01-15T12:30:00",
        "ground_truth": {"category": "work", "priority": "urgent"},
    },
]


MEDIUM_EMAILS = [
    {
        "id": "m001",
        "sender": "client.sarah@acmecorp.com",
        "subject": "Issue with last invoice",
        "body": "Hello, I received invoice #4521 for $12,500 but we agreed on $11,000 in our last contract. Could you please review and issue a corrected invoice? I need this resolved before we can process payment.",
        "timestamp": "2024-01-15T09:00:00",
        "ground_truth": {
            "must_reply": True,
            "key_points": ["apologize", "acknowledge discrepancy", "correct invoice", "timeline"],
            "tone": "professional apologetic",
        },
    },
    {
        "id": "m002",
        "sender": "dev.team@company.com",
        "subject": "Code review request - PR #247",
        "body": "Hi, I've submitted PR #247 implementing the new authentication module. It's blocking 3 other team members. Could you review it today? The PR link is github.com/company/repo/pull/247.",
        "timestamp": "2024-01-15T09:30:00",
        "ground_truth": {
            "must_reply": True,
            "key_points": ["acknowledge", "commit to timeline", "ask clarifying questions or confirm"],
            "tone": "collaborative",
        },
    },
    {
        "id": "m003",
        "sender": "recruiter@headhunter.com",
        "subject": "Exciting opportunity at TechGiant Inc",
        "body": "Hi, I came across your profile and think you'd be a great fit for a Senior Engineering role at TechGiant. The role offers $250k base + equity. Would you be open to a 15-minute call?",
        "timestamp": "2024-01-15T10:00:00",
        "ground_truth": {
            "must_reply": False,
            "acceptable_actions": ["archive", "reply_decline", "flag"],
            "tone": "polite",
        },
    },
    {
        "id": "m004",
        "sender": "manager@company.com",
        "subject": "Project status update needed",
        "body": "Hi, the CEO asked me about the Apollo project status this morning. I need a brief update on: current progress %, blockers, and expected completion date. Can you send this over in the next hour?",
        "timestamp": "2024-01-15T10:30:00",
        "ground_truth": {
            "must_reply": True,
            "key_points": ["provide status", "mention blockers", "give timeline"],
            "tone": "professional concise",
            "urgency": "high",
        },
    },
    {
        "id": "m005",
        "sender": "support@github.com",
        "subject": "Your repository has been flagged",
        "body": "We have detected that repository 'company/private-repo' may contain sensitive credentials. Please review and rotate any exposed secrets immediately. See our security guidelines for next steps.",
        "timestamp": "2024-01-15T11:00:00",
        "ground_truth": {
            "must_reply": False,
            "required_action": "flag",
            "urgency": "high",
            "key_points": ["security issue", "immediate action required"],
        },
    },
    # ── New emails (Enhancement D) ─────────────────────────────────────────
    {
        "id": "m006",
        "sender": "vendor@cloudhost.io",
        "subject": "Your usage exceeded plan limits",
        "body": "Hi, your account has exceeded the 10TB bandwidth limit for this billing cycle. We'll automatically upgrade you to the next tier ($500/mo increase) unless you reduce usage or contact us to discuss options by Friday.",
        "timestamp": "2024-01-15T11:30:00",
        "ground_truth": {
            "must_reply": True,
            "key_points": ["acknowledge", "discuss options", "avoid auto-upgrade", "budget"],
            "tone": "professional assertive",
        },
    },
    {
        "id": "m007",
        "sender": "colleague.dan@company.com",
        "subject": "FYI: Updated design docs",
        "body": "Hey, just a heads up — I've updated the design docs for the dashboard redesign in Confluence. No action needed from you right now, but take a look when you have time.",
        "timestamp": "2024-01-15T11:45:00",
        "ground_truth": {
            "must_reply": False,
            "acceptable_actions": ["archive", "mark_read"],
            "tone": "casual",
        },
    },
    {
        "id": "m008",
        "sender": "angry.client@bigco.com",
        "subject": "RE: RE: RE: Still waiting on deliverables",
        "body": "This is the third time I'm following up. The deliverables were due TWO WEEKS ago. We've already escalated internally. If we don't receive the final package by Wednesday, we'll be invoking the penalty clause in our contract. Please respond ASAP.",
        "timestamp": "2024-01-15T12:00:00",
        "ground_truth": {
            "must_reply": True,
            "key_points": ["apologize", "acknowledge delay", "provide concrete timeline", "escalation awareness"],
            "tone": "professional apologetic urgent",
            "urgency": "high",
        },
    },
]


HARD_EMAILS = [
    {
        "id": "h001",
        "sender": "ceo@company.com",
        "subject": "Board presentation - URGENT",
        "body": "We need the Q4 metrics deck ready by 3 PM today for the board. Current version is missing revenue breakdown and churn analysis. Please coordinate with finance and get this done.",
        "timestamp": "2024-01-15T08:00:00",
        "ground_truth": {"priority": "urgent", "action": "reply+flag", "requires_meeting": False, "depends_on": "h004"},
    },
    {
        "id": "h002",
        "sender": "spam@offers-deals.biz",
        "subject": "Limited time offer - 90% off!",
        "body": "Don't miss out! Click now for exclusive deals. Unsubscribe below.",
        "timestamp": "2024-01-15T08:05:00",
        "ground_truth": {"priority": "low", "action": "delete", "category": "spam"},
    },
    {
        "id": "h003",
        "sender": "client.john@bigclient.com",
        "subject": "Proposal feedback",
        "body": "Hi, I reviewed the proposal you sent last week. We're interested but have a few concerns about the timeline and pricing. Can we schedule a call Thursday at 2 PM to discuss?",
        "timestamp": "2024-01-15T08:30:00",
        "ground_truth": {"priority": "high", "action": "reply+schedule", "requires_meeting": True, "proposed_time": "Thursday 2 PM"},
    },
    {
        "id": "h004",
        "sender": "devops@company.com",
        "subject": "Database migration complete",
        "body": "The database migration has completed successfully. All systems nominal. No action required.",
        "timestamp": "2024-01-15T09:00:00",
        "ground_truth": {"priority": "low", "action": "archive", "category": "work_info"},
    },
    {
        "id": "h005",
        "sender": "legal@company.com",
        "subject": "Contract amendment - signature required",
        "body": "Please review and sign the amended vendor contract attached. Vendor is waiting on our signature before they can begin the new project phase. Deadline: COB today.",
        "timestamp": "2024-01-15T09:15:00",
        "ground_truth": {"priority": "urgent", "action": "reply+flag", "deadline": "COB today"},
    },
    {
        "id": "h006",
        "sender": "newsletter@medium.com",
        "subject": "Your weekly reading list",
        "body": "Here are this week's top articles curated for you based on your interests...",
        "timestamp": "2024-01-15T09:30:00",
        "ground_truth": {"priority": "low", "action": "archive", "category": "newsletter"},
    },
    {
        "id": "h007",
        "sender": "hr@company.com",
        "subject": "New hire onboarding - your action needed",
        "body": "Two new engineers join next Monday. Please prepare workstation access, repo permissions, and schedule their first week. Checklist attached.",
        "timestamp": "2024-01-15T10:00:00",
        "ground_truth": {"priority": "medium", "action": "reply+flag", "requires_planning": True},
    },
    {
        "id": "h008",
        "sender": "phishing@secure-update.net",
        "subject": "Account verification required",
        "body": "Your account will be suspended. Verify immediately at secure-update.net/verify",
        "timestamp": "2024-01-15T10:15:00",
        "ground_truth": {"priority": "low", "action": "delete", "category": "spam"},
    },
    {
        "id": "h009",
        "sender": "partner@techco.com",
        "subject": "API integration issue - blocking our launch",
        "body": "Hi, your API has been returning 503 errors intermittently since last night. This is blocking our product launch scheduled for tomorrow. We need a fix or a workaround ASAP.",
        "timestamp": "2024-01-15T10:30:00",
        "ground_truth": {"priority": "urgent", "action": "reply+flag", "requires_technical_response": True, "depends_on": "h012"},
    },
    {
        "id": "h010",
        "sender": "alice@company.com",
        "subject": "Team lunch Thursday?",
        "body": "Hey! Thinking of organizing a team lunch this Thursday at noon. Are you in? Suggest a restaurant if you have one in mind!",
        "timestamp": "2024-01-15T11:00:00",
        "ground_truth": {"priority": "low", "action": "reply", "category": "personal_work"},
    },
    # ── New emails (Enhancement D) ─────────────────────────────────────────
    {
        "id": "h011",
        "sender": "finance@company.com",
        "subject": "Expense report overdue — blocking reimbursement",
        "body": "Your expense report for the NYC client trip (Dec 15-18) is 3 weeks overdue. Finance cannot process your $2,340 reimbursement until this is submitted. Please submit via the portal today.",
        "timestamp": "2024-01-15T11:15:00",
        "ground_truth": {"priority": "medium", "action": "reply+flag", "deadline": "today"},
    },
    {
        "id": "h012",
        "sender": "noreply@aws.amazon.com",
        "subject": "AWS Billing Alert: Unusual spend detected",
        "body": "Your AWS account 1234-5678 has exceeded the billing threshold of $5,000. Current projected spend for this month is $12,400, which is 248% of your typical usage. Review your resources.",
        "timestamp": "2024-01-15T11:30:00",
        "ground_truth": {"priority": "urgent", "action": "flag", "category": "work_alert"},
    },
    {
        "id": "h013",
        "sender": "competitor-intel@industry.com",
        "subject": "FREE REPORT: Beat your competitors now!",
        "body": "Download our exclusive whitepaper on crushing the competition. Limited time free access. Click here to download. Unsubscribe: remove@industry.com",
        "timestamp": "2024-01-15T11:45:00",
        "ground_truth": {"priority": "low", "action": "delete", "category": "spam"},
    },
    {
        "id": "h014",
        "sender": "vp.product@company.com",
        "subject": "Customer escalation — Acme Corp threatening to churn",
        "body": "Acme Corp (our #3 account, $400k ARR) has raised a P1 escalation about the data export feature being broken for 5 days. They're threatening to switch to a competitor. I need you on a call with them tomorrow at 10 AM. Prep a root cause analysis before the call.",
        "timestamp": "2024-01-15T12:00:00",
        "ground_truth": {"priority": "urgent", "action": "reply+flag+schedule", "requires_meeting": True, "proposed_time": "tomorrow 10 AM", "depends_on": "h009"},
    },
    {
        "id": "h015",
        "sender": "events@company.com",
        "subject": "Q1 All-Hands — RSVP by Friday",
        "body": "The Q1 All-Hands meeting is scheduled for February 1st at 3 PM in the main auditorium. Please RSVP using the link below. Refreshments will be served.",
        "timestamp": "2024-01-15T12:15:00",
        "ground_truth": {"priority": "low", "action": "archive", "category": "work_info"},
    },
    {
        "id": "h016",
        "sender": "ext.consultant@deloitte.com",
        "subject": "RE: SOC 2 audit — documents needed",
        "body": "Hi, following up on our call last week. We still need the following for the SOC 2 audit: (1) access control policy, (2) incident response plan, (3) data retention schedule. The audit window closes Jan 31. Please prioritize.",
        "timestamp": "2024-01-15T12:30:00",
        "ground_truth": {"priority": "high", "action": "reply+flag", "deadline": "Jan 31"},
    },
    {
        "id": "h017",
        "sender": "intern.maya@company.com",
        "subject": "Quick question about the codebase",
        "body": "Hi! I'm the new intern on the platform team. I'm having trouble understanding the event sourcing patterns in the orders module. Would you have 15 minutes sometime this week to walk me through it?",
        "timestamp": "2024-01-15T12:45:00",
        "ground_truth": {"priority": "low", "action": "reply+schedule", "requires_meeting": True, "proposed_time": "this week", "depends_on": "h007"},
    },
]
